theme = "kanagawa-custom"

[editor]
true-color  = true
cursorline  = true
color-modes = true
bufferline  = "multiple"

[editor.cursor-shape]
insert= "bar"

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "→"

[editor.indent-guides]
render = true

[keys.normal]
"C-s"   = ":w"
"tab"   = ":buffer-next"
"S-tab" = ":buffer-previous"

[keys.insert]
"C-space" = "completion"