theme = "modern"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 64

[[block]]
block = "music"
buttons = ["play","next"]
marquee = false
dynamic_width = true
hide_when_empty = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_avail_percents}"
warning_mem = 50.0
critical_mem = 90.0
clickable = false
interval = 5

[[block]]
block = "load"
interval = 10
format = "{1m}"

[[block]]
block = "temperature"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "sound"
driver = "pulseaudio"
max_vol = 100
on_click = "pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status"

#[[block]]
#block = "custom"
#command = "$HOME/bin/mailcheck"
#json = true
#interval = 60
#on_click = "xdg-open 'https://mail.google.com'"
#hide_when_empty = true

#[[block]]
#block = "custom"
#command = "$HOME/go/bin/iwstatus"
#json = true
#interval = 5

[[block]]
block = "weather"
format = "{apparent}"
service = { name = "openweathermap", api_key = "db905d7c63b87b5477300f06b6c55806", city_id = "4259418", units = "metric" }

[[block]]
block = "time"
interval = 5
format = "%A %F %R"
